<?php
/*
* Pkgroup/Customeroffer/block/index
*/
$categories = $block->getCategoryCollectionbyids();
$price = $this->helper('Magento\Framework\Pricing\Helper\Data');

?>
<div class="offer-products-wrapper">
	<ul class="category-wrapper">
		<li class="title">Select Category</li>
		<?php foreach($categories as $_category): ?>
			<li data-catactive="active_id_<?= $_category->getId() ?>" class="catid_<?= $_category->getId() ?> select-tab"><?= $_category->getName() ?></li>
		<?php endforeach; ?>
	</ul>
	
	<?php 
		foreach($categories as $_category): 
		$_productCollection = $block->getProductCollectionByCategories([$_category->getId()]);
		$cd = count($_productCollection);
	?>
		<div class="category-products-wrapper active_id_<?= $_category->getId()?>" style="display:none;">
			<?php if($cd == 0): ?>
			<span class="notification">No item found!</span>
			<?php endif; ?>
			<?php if($cd != 0): ?>
			<ul class="cat_1">
				<?php foreach($_productCollection as $_product): ?>
					<li class="item">
						<div class="product-detail-wrapper">
							<input type="radio" name="proudct_id_<?= $_category->getId() ?>" value="<?= $_product->getId(); ?>">
							<img src="<?= $block->getImageOriginalWidth($_product, 'product_small_image') ?>"/>
							<span class="product-name"><?= $_product->getName(); ?></span>
							<span class="product-price"><?= $price->currency(number_format($_product->getFinalPrice(),2),true,false); ?></span>
						</div>
					</li>
				<?php endforeach; ?>
			</ul>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>
	<div class="checkout_action_wrapper">
		<form id="offerpage" action="<?= $this->getUrl('offer/index/addtocart') ?>" method="post">
			<input type="hidden" name="productsids" value="">
			<button type="submit" class="action primary checkout" value="virtual">Checkout</button>
		</form>
	</div>
</div>

<style>
ul.category-wrapper li {
    float: left;
    padding: 1%;
    width: 18%;
    list-style: none;
    background: #000;
    color: #fff;
    text-align: center;
	cursor:pointer;
}

ul.category-wrapper li:hover { 
background:#0000ff;
}

ul.category-wrapper li.active { 
background:#0000ff;
}
ul.category-wrapper li.title:hover { 
background:#000 !important;
cursor:default !important;
}

.offer-products-wrapper {
    border: 1px solid #ccc;
}

ul.category-wrapper {
    width: 100%;
    float: left;
    margin: 0 !important;
    padding: 0 !important;
}

ul.cat_1 li.item {
    float: left;
    list-style: none;
    width: 22%;
    padding: 1%;
    height: 353px;
    border: 0.5px solid #ccc;
    margin: 2px;
}

ul.cat_1 {
    width: 100%;
    padding: 0;
    margin: 0;
}

span.product-price {
    width: 100%;
    float: left;
    color: #0000ff;
}

.checkout_action_wrapper {
    width: 100%;
    float: left;
    height: 69px;
    background: #ccc;
}
</style>
<script>
require(['jquery', 'jquery/ui'], function($){
  $(document).ready( function() {
	 $(".category-products-wrapper:first").show();
	 $(".select-tab:first").addClass("active");
     $('.select-tab').click(function(){
		 $(".select-tab").removeClass("active");
		 $(this).addClass("active");
		 $(".category-products-wrapper").hide();
		 var idactive = $(this).data("catactive");
		 $("."+idactive).show();
	 });
	 
	 $(".checkout").click(function(e){
		 e.preventDefault();
		var ids = jQuery("input[type='radio'][name^='proudct_id_']:checked");
		var products = [];
		ids.each(function(i){
			products[i] = jQuery(this).val();
		});
		$("input[name='productsids']").val(products.join(","));
		$("#offerpage").submit();
	 });
	 
	 $(".item").click(function(){
		 $(this).find("input").attr("checked",true);
	 });
	 
  });
});
</script>